version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack-config-generator
    versions:
    - 1.0.14
    - 1.0.15
    - 1.0.16
    - 1.0.17
    - 1.0.18
  - dependency-name: "@types/prismjs"
    versions:
    - 1.16.2
    - 1.16.3
    - 1.16.4
  - dependency-name: prism-themes
    versions:
    - 1.5.0
    - 1.6.0
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: bl
    versions:
    - 4.0.4
    - 4.1.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
