name: Documentation deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Documentation
      run: |
        cd docs/
        npm install
        npm run build
    - name: Deploy on GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: docs/build/
